name: Linux Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.14]
    runs-on: ubuntu-latest

    steps:
    - name: Install Cgo dependencies
      run: sudo apt install libasound2-dev

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Run tests
      run: go test -race ./...
